name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
    #   - name: Generate prisma client
    #     run: cd packages/db && npx prisma generate && cd ../.. only if u have prisma
      - name: Turbo Build
        run: npm run build
