name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setups Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dcokerfile.web
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/webapp:latest

      - name: Verify Docker image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/webapp:latest
